version: '3.8'

services:
  minesweeper:
    build: .
    container_name: minesweeper-game
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY}:/tmp/.docker.xauth:rw
      - ./data:/app/data:rw
    network_mode: host
    stdin_open: true
    tty: true
